
name: build-windows
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean core build
        run: if (Test-Path core\build) { Remove-Item -Recurse -Force core\build }

      - name: Build C++ core
        run: |
          cmake -S core -B core/build -G "Visual Studio 17 2022" -A x64
          cmake --build core/build --config Release --parallel

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build C# UI
        run: |
          copy core\build\Release\mirroraudio_core.exe ui\
          dotnet restore ui\MirrorAudio.UI.csproj
          dotnet publish ui\MirrorAudio.UI.csproj -c Release -o out

      - name: Package app
        run: |
          mkdir dist
          copy out\* dist\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MirrorAudio-Windows-x64
          path: dist
